Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-08, with the labels that each got.

#220 212 수정됨 상태변화 오류
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/global/common/BaseEntity.java
  src/main/java/org/prgms/locomocoserver/inquiries/domain/Inquiry.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/location/MogakkoLocation.java
  src/main/java/org/prgms/locomocoserver/replies/domain/Reply.java
  src/main/java/org/prgms/locomocoserver/report/domain/Report.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
Labels: refactor

#221 Test 98 모각코 참여 검증
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/test/java/org/prgms/locomocoserver/global/TestFactory.java
  src/test/java/org/prgms/locomocoserver/inquiries/application/InquiryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: feat, fix, refactor, test

#227 Feat 222 모각코 법정동 추가
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MidpointService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Location.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/location/MogakkoLocation.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/midpoint/Midpoint.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/vo/AddressInfo.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/LocationInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/Place.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MidpointDto.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MidpointServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoControllerTest.java
Labels: feat, refactor

#223 143 채팅방 이미지 기능 구현
  .github/workflows/build.yml
  src/main/java/org/prgms/locomocoserver/chat/application/ChatImageService.java
  src/main/java/org/prgms/locomocoserver/chat/application/ChatMessagePolicy.java
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MongoChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MySqlChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongo.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
  src/main/java/org/prgms/locomocoserver/image/application/ImageService.java
  src/main/java/org/prgms/locomocoserver/image/exception/ImageErrorType.java
  src/test/java/org/prgms/locomocoserver/chat/application/MongoChatServiceTest.java
  src/test/java/org/prgms/locomocoserver/global/TestFactory.java
  src/test/resources/스누피4.jpeg
Labels: feat

#230 228 사용자 정보 검증코드
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserErrorType.java
  src/main/java/org/prgms/locomocoserver/user/vo/BirthVo.java
  src/main/java/org/prgms/locomocoserver/user/vo/NicknameVo.java
  src/test/java/org/prgms/locomocoserver/user/application/UserServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserTest.java
Labels: refactor, test

#237 Fix 236 최초 모각코 리스트 안나오는 에러 수정
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: fix

#235 Feat 232 로그 파일 따로 빼기
  .github/workflows/build-deploy.yml
  src/main/resources/logback-spring.xml
Labels: feat

#234 233 인증처리 리팩토링
  src/main/java/org/prgms/locomocoserver/global/annotation/GetUser.java
  src/main/java/org/prgms/locomocoserver/global/config/UserArgumentResolver.java
  src/main/java/org/prgms/locomocoserver/global/config/WebConfig.java
  src/main/java/org/prgms/locomocoserver/global/context/UserContext.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/user/application/RefreshTokenService.java
  src/main/java/org/prgms/locomocoserver/user/application/TokenService.java
  src/main/java/org/prgms/locomocoserver/user/presentation/GithubController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/KakaoController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat, refactor

#239 Fix 238 모각코 리스트 반환 쿼리 재구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/LocationSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/SearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/TitleAndContentSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/CursorDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoControllerTest.java
Labels: fix, refactor
