Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-10, with the labels that each got.

#247 244 데이터베이스별 데이터 분리
  .gitignore
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MongoChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongo.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoCustomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoCustomRepositoryImpl.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatRoomMongo.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatRoomMongoRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/querydsl/ChatRoomCustomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/querydsl/ChatRoomCustomRepositoryImpl.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatUserInfo.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/test/java/org/prgms/locomocoserver/chat/application/MongoChatServiceTest.java
  src/test/java/org/prgms/locomocoserver/chat/domain/ChatRoomMongoRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/chat/repository/ChatRoomRepositoryTest.java
Labels: fix, refactor

#250 Test 248 검색 서비스 테스트 코드 작성
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/SearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/TotalSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoFilterRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/location/MogakkoLocation.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceFindAllTest.java
Labels: refactor, test

#253 refactor 252 클라이언트의 잘못된 요청에 대해서는 슬랙 알림을 전송하지 않음.
  src/main/java/org/prgms/locomocoserver/global/exception/GlobalExceptionHandler.java
Labels: fix, refactor

#257 256 마이페이지 인증필터 재적용
  src/main/java/org/prgms/locomocoserver/global/config/AppConfig.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/global/property/AuthProperties.java
  src/main/java/org/prgms/locomocoserver/global/property/CorsProperties.java
  src/main/java/org/prgms/locomocoserver/user/application/RefreshTokenService.java
  src/main/java/org/prgms/locomocoserver/user/domain/RefreshToken.java
  src/main/java/org/prgms/locomocoserver/user/presentation/KakaoController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
  src/test/java/org/prgms/locomocoserver/user/application/RefreshTokenServiceTest.java
Labels: feat, fix, refactor

#255 251 채팅방 잔오류 해결
  src/main/java/org/prgms/locomocoserver/chat/application/ChatActivityService.java
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MongoChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatParticipant.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoCustomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoCustomRepositoryImpl.java
  src/main/java/org/prgms/locomocoserver/chat/domain/querydsl/ChatParticipantCustomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/querydsl/ChatParticipantCustomRepositoryImpl.java
  src/main/java/org/prgms/locomocoserver/chat/domain/querydsl/ChatRoomCustomRepositoryImpl.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatActivityRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/exception/ChatErrorType.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/ChatActivityController.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/domain/UserRepository.java
  src/main/java/org/prgms/locomocoserver/user/domain/querydsl/UserCustomRepository.java
  src/main/java/org/prgms/locomocoserver/user/domain/querydsl/UserCustomRepositoryImpl.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/user/application/UserServiceTest.java
Labels: feat, fix, refactor, test
