Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-02, with the labels that each got.

#10 Feature 6 mogakko 엔티티 구성 및 기본 crud 구성
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat

#15 14 swagger 적용
  build.gradle
  src/main/java/org/prgms/locomocoserver/global/config/SwaggerConfig.java
  src/main/java/org/prgms/locomocoserver/global/config/WebSecurityConfig.java
  src/main/java/org/prgms/locomocoserver/inquires/presentation/InquireController.java
Labels: feat

#19 Feature 13 category tag 엔티티를 추가
  src/main/java/org/prgms/locomocoserver/categories/application/CategoryService.java
  src/main/java/org/prgms/locomocoserver/categories/domain/Category.java
  src/main/java/org/prgms/locomocoserver/categories/domain/CategoryRepository.java
  src/main/java/org/prgms/locomocoserver/categories/domain/CategoryType.java
  src/main/java/org/prgms/locomocoserver/categories/presentation/CategoryController.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTags.java
  src/main/java/org/prgms/locomocoserver/tags/application/TagService.java
  src/main/java/org/prgms/locomocoserver/tags/domain/Tag.java
  src/main/java/org/prgms/locomocoserver/tags/domain/TagRepository.java
  src/main/java/org/prgms/locomocoserver/tags/presentation/TagController.java
Labels: feat

#21 Feature 18 mogakko를 생성할 수 있다
  src/main/java/org/prgms/locomocoserver/categories/domain/Category.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MGCType.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTag.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/SelectedTagsDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoCreateResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/tags/domain/Tag.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: feat

#22 17 깃허브 로그인 구현
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/dto/OAuthUserInfoDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/github/GithubTokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/github/GithubUserInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoUserInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/GithubController.java
Labels: feat

#24 docs: swagger 정보 입력
  src/main/java/org/prgms/locomocoserver/user/dto/github/GithubTokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/github/GithubUserInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoAccountDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoTokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoUserInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/GithubController.java
Labels: docs

#23 Feature 20 category tag 전달
  src/main/java/org/prgms/locomocoserver/categories/application/CategoryService.java
  src/main/java/org/prgms/locomocoserver/categories/domain/CategoryRepository.java
  src/main/java/org/prgms/locomocoserver/categories/dto/response/CategoriesWithTagsDto.java
  src/main/java/org/prgms/locomocoserver/categories/presentation/CategoryController.java
  src/main/java/org/prgms/locomocoserver/global/common/dto/Results.java
  src/main/java/org/prgms/locomocoserver/tags/dto/TagsInfoDto.java
  src/test/java/org/prgms/locomocoserver/categories/application/CategoryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: feat

#28 26 회원가입 초기정보 입력
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/domain/UserRepository.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoTokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserInitInfoRequestDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/TokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserInfoDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserLoginResponse.java
  src/main/java/org/prgms/locomocoserver/user/presentation/GithubController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/KakaoController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#30 fix: 카카오 dto 사용하지 않는 데이터 삭제
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoAccountDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/kakao/KakaoUserInfoResponseDto.java
Labels: bug

#32 fix #31 MGCType 삭제
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MGCType.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: fix

#34 Feature 8 모각코 rud 관련 엔티티 생성
  src/main/java/org/prgms/locomocoserver/inquires/application/InquireService.java
  src/main/java/org/prgms/locomocoserver/inquires/domain/Inquire.java
  src/main/java/org/prgms/locomocoserver/inquires/domain/InquireRepository.java
  src/main/java/org/prgms/locomocoserver/inquiries/application/InquiryService.java
  src/main/java/org/prgms/locomocoserver/inquiries/domain/Inquiry.java
  src/main/java/org/prgms/locomocoserver/inquiries/domain/InquiryRepository.java
  src/main/java/org/prgms/locomocoserver/inquiries/presentation/InquiryController.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTag.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/Participant.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/replies/domain/Reply.java
  src/main/java/org/prgms/locomocoserver/replies/domain/ReplyRepository.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: feat

#37 feat: cors config 파일 추가
  src/main/java/org/prgms/locomocoserver/global/config/CorsConfig.java
Labels: feat

#39 38 method cors 처리
  src/main/java/org/prgms/locomocoserver/global/config/CorsConfig.java
  src/main/java/org/prgms/locomocoserver/global/config/WebConfig.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/GithubController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/KakaoController.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: fix

#41 Feature 33 모각코 디테일 정보 읽기 구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoDetailResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoParticipantDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/user/domain/UserRepository.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserBriefInfoDto.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: feat

#43 Feature 40 모각코 생성에 작성자 정보 추가
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/SelectedTagsDto.java
  src/test/java/org/prgms/locomocoserver/categories/application/CategoryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: feat

#44 35 웹소켓 기반 채팅구현
  build.gradle
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/enums/MessageType.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
  src/main/java/org/prgms/locomocoserver/global/config/WebSocketConfig.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#51 49 user review api 생성
  src/main/java/org/prgms/locomocoserver/review/application/ReviewContentService.java
  src/main/java/org/prgms/locomocoserver/review/application/ReviewService.java
  src/main/java/org/prgms/locomocoserver/review/domain/Review.java
  src/main/java/org/prgms/locomocoserver/review/domain/ReviewRepository.java
  src/main/java/org/prgms/locomocoserver/review/domain/data/ReviewContent.java
  src/main/java/org/prgms/locomocoserver/review/domain/data/ReviewContentRepository.java
  src/main/java/org/prgms/locomocoserver/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/review/dto/response/ReviewContentDto.java
  src/main/java/org/prgms/locomocoserver/review/dto/response/ReviewDto.java
  src/main/java/org/prgms/locomocoserver/review/presentation/ReviewController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/TokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserInfoDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
  src/main/resources/sql/data.sql
Labels: feat, docs

#52 Feature 48 문의 모각코 리스트 목 api
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/request/InquiryCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/request/InquiryDeleteRequestDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/request/InquiryUpdateRequestDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/response/InquiryResponseDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/response/InquiryUpdateResponseDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/presentation/InquiryController.java
  src/main/java/org/prgms/locomocoserver/location/dto/LocationInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoFilterRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoCreateResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoSimpleInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: feat

#55 54 채팅방 채팅 조회 기능
  .github/workflows/gradle.yml
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatMessage.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatMessageRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/enums/MessageType.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/ChatRoomController.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserBriefInfoDto.java
  src/main/resources/sql/data.sql
Labels: feat

#57 Feature 50 location 엔티티 추가 및 적용
  src/main/java/org/prgms/locomocoserver/location/domain/Location.java
  src/main/java/org/prgms/locomocoserver/location/domain/LocationRepository.java
  src/main/java/org/prgms/locomocoserver/location/dto/LocationInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoFilterRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoUpdateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat

#62 Feature 61 category에 입력 타입 추가
  src/main/java/org/prgms/locomocoserver/categories/application/CategoryService.java
  src/main/java/org/prgms/locomocoserver/categories/domain/Category.java
  src/main/java/org/prgms/locomocoserver/categories/domain/CategoryInputType.java
  src/main/java/org/prgms/locomocoserver/categories/dto/response/CategoriesWithTagsDto.java
Labels: feat

#64 Feature 46 모각코 리스트 필터링 구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoSimpleInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/test/java/org/prgms/locomocoserver/categories/application/CategoryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: feat

#70 fix #69: 업데이트 된 모각코와 관련된 태그만 모각코-태그에서 삭제되도록 수정
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
Labels: fix

#77 60 user 로그아웃 구현
  src/main/java/org/prgms/locomocoserver/review/application/ReviewService.java
  src/main/java/org/prgms/locomocoserver/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/review/presentation/ReviewController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat
