Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-05, with the labels that each got.

#184 177 채팅 mongoDB 도입
  build.gradle
  src/main/java/org/prgms/locomocoserver/chat/application/ChatMessagePolicy.java
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MongoChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MySqlChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongo.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatMessageMongoRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatRoomMongo.java
  src/main/java/org/prgms/locomocoserver/chat/domain/mongo/ChatRoomMongoRepository.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/ChatRoomController.java
  src/test/java/org/prgms/locomocoserver/chat/application/MongoChatServiceTest.java
  src/test/java/org/prgms/locomocoserver/chat/domain/ChatRoomMongoRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/global/TestFactory.java
Labels: feat

#186 185 mongodb 최종적용
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MongoChatMessageService.java
  src/main/java/org/prgms/locomocoserver/chat/application/MySqlChatMessageService.java
Labels: feat

#190 chore: 빌드 및 배포 방식 변경
  .github/workflows/build-deploy-dev.yml
  .github/workflows/build-deploy.yml
  .github/workflows/build.yml
  Dockerfile
Labels: refactor

#191 refactor: mysql 테스트 로컬에서 구동되도록 수정
  .github/workflows/build-deploy.yml
  .github/workflows/build.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: refactor, test

#192 Update build-deploy.yml
  .github/workflows/build-deploy.yml
Labels: refactor

#194 fix: S3 버킷 이미지 삽입 도중 ACL 이용 부분 삭제
  src/main/java/org/prgms/locomocoserver/image/application/ImageService.java
Labels: fix

#195 fix: ACL 이용 부분 다시 적용
  src/main/java/org/prgms/locomocoserver/image/application/ImageService.java
Labels: fix

#196 fix: 도시 검색이 확실하게 되도록 수정
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
Labels: fix

#200 189 리드미 정리
  README.md
  썸네일용.png
Labels: docs

#204 199 fcm 데이터 mongodb 이전
  src/main/java/org/prgms/locomocoserver/user/application/DeviceKeyService.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/mongo/DeviceKey.java
  src/main/java/org/prgms/locomocoserver/user/domain/mongo/DeviceKeyMongoRepository.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/DeviceKeyUpdateRequest.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/DeviceKeyDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
  src/test/java/org/prgms/locomocoserver/user/application/DeviceKeyServiceTest.java
  src/test/java/org/prgms/locomocoserver/user/application/UserServiceTest.java
Labels: feat, test

#201 Feature 187 중간지점 응용 서비스 생성
  src/main/java/org/prgms/locomocoserver/global/common/Pair.java
  src/main/java/org/prgms/locomocoserver/global/config/AppConfig.java
  src/main/java/org/prgms/locomocoserver/location/domain/LocationRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MidpointService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/findroad/FindRoadFactory.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/findroad/FindRoadInfo.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/findroad/KakaoFindRoadInfo.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/findroad/OdsayFindRoadInfo.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/mapsearch/KakaoMapSearch.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/recommend/MidpointRecommendService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Location.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/location/MogakkoLocation.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/location/MogakkoLocationRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/midpoint/Midpoint.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/midpoint/MidpointRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/Participant.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/LocationInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/Place.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/StartingPointDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/MogakkoUpdateRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MidpointDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoSimpleInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoMidpointController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/global/TestFactory.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/recommend/MidpointRecommendServiceTest.java
Labels: feat, refactor, test
