Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-04, with the labels that each got.

#175 Refactor 174 필터링 최적화
  src/main/java/org/prgms/locomocoserver/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/exception/MogakkoErrorCode.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat, refactor

#176 173 redis 적용
  build.gradle
  src/main/java/org/prgms/locomocoserver/global/config/RedisConfig.java
  src/main/java/org/prgms/locomocoserver/user/application/RefreshTokenService.java
  src/main/java/org/prgms/locomocoserver/user/domain/RefreshToken.java
  src/main/java/org/prgms/locomocoserver/user/domain/RefreshTokenRepository.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/TokenResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserErrorType.java
  src/main/java/org/prgms/locomocoserver/user/presentation/KakaoController.java
  src/test/java/org/prgms/locomocoserver/global/AbstractRedisContainerBaseTest.java
  src/test/java/org/prgms/locomocoserver/user/application/RefreshTokenServiceTest.java
Labels: feat

#179 Feature 178 에러 발생 슬랙 연동
  build.gradle
  src/main/java/org/prgms/locomocoserver/global/common/SlackAlertService.java
  src/main/java/org/prgms/locomocoserver/global/common/dto/SlackErrorAlertDto.java
  src/main/java/org/prgms/locomocoserver/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgms/locomocoserver/inquiries/application/InquiryService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/exception/MogakkoErrorType.java
  src/main/java/org/prgms/locomocoserver/mogakkos/exception/MogakkoException.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTest.java
Labels: feat

#181 인증 api 추가
  src/main/java/org/prgms/locomocoserver/global/config/AppConfig.java
  src/main/java/org/prgms/locomocoserver/global/exception/ErrorCode.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
Labels: feat

#182 Test 145 모각코 필터링 서비스 테스트
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: refactor, test
