Repository Ogu-Family/Locomoco_BE, pull requests merged in 2024-03, with the labels that each got.

#79 56 user chat 검증로직 추가
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatMessageDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/global/common/BaseEntity.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserInitInfoRequestDto.java
Labels: feat

#84 81 채팅 수정사항 반영
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatMessageRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/ChatRoomController.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
Labels: feat, fix

#91 fix 90 시간 타입 수정
  src/main/java/org/prgms/locomocoserver/global/common/BaseEntity.java
Labels: fix

#88 Feature 82 통합검색 구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/SearchType.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/LocationSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/SearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/TotalSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/SearchRepositoryDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat

#89 Feature 66 문의 읽기, 삭제 구현
  src/main/java/org/prgms/locomocoserver/inquiries/application/InquiryService.java
  src/main/java/org/prgms/locomocoserver/inquiries/domain/InquiryRepository.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/response/InquiryResponseDto.java
  src/main/java/org/prgms/locomocoserver/inquiries/presentation/InquiryController.java
Labels: feat

#94 93 채팅 상세 수정사항
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
Labels: fix

#92 78 사용자 프로필 이미지 추가
  build.gradle
  src/main/java/org/prgms/locomocoserver/global/config/AwsS3Config.java
  src/main/java/org/prgms/locomocoserver/image/application/ImageService.java
  src/main/java/org/prgms/locomocoserver/image/domain/Image.java
  src/main/java/org/prgms/locomocoserver/image/domain/ImageRepository.java
  src/main/java/org/prgms/locomocoserver/image/dto/ImageDto.java
  src/main/java/org/prgms/locomocoserver/image/presentaion/ImageController.java
  src/main/java/org/prgms/locomocoserver/inquiries/dto/response/InquiryResponseDto.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserBriefInfoDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserInfoDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#96 Fix 86 조회 수 로직 추가 및 디테일 페이지 api 변경
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoInfoDto.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
Labels: feat, fix

#97 95 웹소켓 연결 끊김 현상
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/application/StompChatService.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
Labels: fix

#101 Feature 87 모각코 참여 참여취소 구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/request/ParticipationRequestDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/ParticipationCheckingDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoParticipationController.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
Labels: feat

#107 fix 106 더티 체킹 비활성화 및 도메인의 조회 수 값도 증가
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
Labels: fix

#108 fix 106 트랜잭션을 따로 처리
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
Labels: fix

#102 99 모각코 좋아요 기능 구현
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/likes/MogakkoLike.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/likes/MogakkoLikeRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoLikeDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
  src/main/resources/sql/data.sql
Labels: feat

#112 109 신고 CRUD
  src/main/java/org/prgms/locomocoserver/report/application/ReportService.java
  src/main/java/org/prgms/locomocoserver/report/domain/Report.java
  src/main/java/org/prgms/locomocoserver/report/domain/ReportRepository.java
  src/main/java/org/prgms/locomocoserver/report/dto/ReportDto.java
  src/main/java/org/prgms/locomocoserver/report/dto/request/ReportCreateRequest.java
  src/main/java/org/prgms/locomocoserver/report/dto/request/ReportUpdateRequest.java
  src/main/java/org/prgms/locomocoserver/report/presentation/ReportController.java
Labels: feat

#113 110 후기 조회 추가
  src/main/java/org/prgms/locomocoserver/review/application/ReviewService.java
  src/main/java/org/prgms/locomocoserver/review/domain/Review.java
  src/main/java/org/prgms/locomocoserver/review/domain/ReviewRepository.java
  src/main/java/org/prgms/locomocoserver/review/dto/response/ReviewDto.java
  src/main/java/org/prgms/locomocoserver/review/presentation/ReviewController.java
Labels: feat

#111 Feature 103 블랙리스트 추가 삭제 조회 구현
  src/main/java/org/prgms/locomocoserver/blacklist/application/BlacklistService.java
  src/main/java/org/prgms/locomocoserver/blacklist/domain/Blacklist.java
  src/main/java/org/prgms/locomocoserver/blacklist/domain/BlacklistRepository.java
  src/main/java/org/prgms/locomocoserver/blacklist/dto/request/BlacklistRequestDto.java
  src/main/java/org/prgms/locomocoserver/blacklist/presentation/BlacklistController.java
Labels: feat

#115 114 좋아요 기능 구현 방식 변경
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoLikeService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/likes/MogakkoLike.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/likes/MogakkoLikeRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoLikeDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
Labels: refactor

#116 58 사용자 인증 추가
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatMessageRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/global/config/AppConfig.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/user/application/AuthenticationService.java
Labels: feat

#118 [Urgent] FE 통신 오류 수정 Master 변경사항 반영
  src/main/java/org/prgms/locomocoserver/chat/application/StompChatService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/global/config/AppConfig.java
  src/main/java/org/prgms/locomocoserver/global/config/WebConfig.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/global/filter/CorsFilter.java
Labels: fix

#121 119 신고 세부사항
  src/main/java/org/prgms/locomocoserver/report/application/ReportService.java
  src/main/java/org/prgms/locomocoserver/report/dto/ReportDto.java
Labels: refactor

#123 117 user custom exception 추가
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/image/application/ImageService.java
  src/main/java/org/prgms/locomocoserver/image/exception/ImageErrorType.java
  src/main/java/org/prgms/locomocoserver/image/exception/ImageException.java
  src/main/java/org/prgms/locomocoserver/image/exception/ImageExceptionHandler.java
  src/main/java/org/prgms/locomocoserver/image/presentaion/ImageController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserErrorType.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserException.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserExceptionHandler.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#127 125 user 관련 수정사항 적용
  build.gradle
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/global/config/SwaggerConfig.java
  src/main/java/org/prgms/locomocoserver/global/exception/ExpiredTokenException.java
  src/main/java/org/prgms/locomocoserver/global/exception/InvalidTokenException.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/user/application/AuthenticationService.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserUpdateRequest.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#126 Feature 124 모각코 생성 후 채팅방 자동 생성
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatParticipant.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoom.java
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatCreateRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatEnterRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/StompChatController.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
Labels: feat, fix

#132 Feature 130 마이페이지 모각코 목록 개수만 넘겨주고 모각코 목록 dto는 간소화
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/likes/MogakkoLikeRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserMyPageDto.java
  src/main/java/org/prgms/locomocoserver/user/presentation/UserController.java
Labels: feat

#134 feature 131 DTO에 생성 시간, 수정 시간 추가
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoInfoDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/response/MogakkoSimpleInfoResponseDto.java
  src/main/java/org/prgms/locomocoserver/review/dto/response/ReviewDto.java
Labels: feat

#137 Fix 136 모각코 생성자는 자동 참여
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
Labels: feat, fix

#139 138 모각코와 연결된 채팅방 조회 api
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/presentation/ChatRoomController.java
Labels: feat

#141 140 chatmessagerequestdto 필드 수정
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/dto/request/ChatMessageRequestDto.java
Labels: fix

#146 Refactor 142 모각코 리스트 페이징 사이즈 파라미터 추가
  src/main/java/org/prgms/locomocoserver/location/domain/LocationRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/LocationSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/SearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/TotalSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat, refactor

#149 Fix 148 job 태그화
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/domain/enums/Job.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserInitInfoRequestDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserUpdateRequest.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserInfoDto.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/inquiries/application/InquiryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: fix, refactor

#150 master 병합
  src/main/java/org/prgms/locomocoserver/location/domain/LocationRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/LocationSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/SearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/TotalSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/User.java
  src/main/java/org/prgms/locomocoserver/user/domain/enums/Job.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserInitInfoRequestDto.java
  src/main/java/org/prgms/locomocoserver/user/dto/request/UserUpdateRequest.java
  src/main/java/org/prgms/locomocoserver/user/dto/response/UserInfoDto.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
  src/test/java/org/prgms/locomocoserver/inquiries/application/InquiryServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/application/MogakkoServiceTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
  src/test/java/org/prgms/locomocoserver/user/domain/UserRepositoryTest.java
Labels: feat

#147 129 커스텀 예외코드 적용
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatRoomRepository.java
  src/main/java/org/prgms/locomocoserver/chat/exception/ChatErrorType.java
  src/main/java/org/prgms/locomocoserver/chat/exception/ChatException.java
  src/main/java/org/prgms/locomocoserver/global/common/dto/ErrorResponse.java
  src/main/java/org/prgms/locomocoserver/global/exception/AuthException.java
  src/main/java/org/prgms/locomocoserver/global/exception/ErrorCode.java
  src/main/java/org/prgms/locomocoserver/global/exception/ExpiredTokenException.java
  src/main/java/org/prgms/locomocoserver/global/exception/InvalidTokenException.java
  src/main/java/org/prgms/locomocoserver/global/filter/AuthenticationFilter.java
  src/main/java/org/prgms/locomocoserver/global/filter/ExceptionHandlerFilter.java
  src/main/java/org/prgms/locomocoserver/user/application/AuthenticationService.java
  src/main/java/org/prgms/locomocoserver/user/exception/UserErrorType.java
  src/main/java/org/prgms/locomocoserver/user/vo/BirthVo.java
  src/main/java/org/prgms/locomocoserver/user/vo/EmailVo.java
  src/main/java/org/prgms/locomocoserver/user/vo/TemperatureVo.java
Labels: feat

#152 Fix 151 유저 생성 시 자동으로 device key 테이블에도 추가
  src/main/java/org/prgms/locomocoserver/user/application/UserService.java
  src/main/java/org/prgms/locomocoserver/user/domain/DeviceKey.java
  src/main/java/org/prgms/locomocoserver/user/domain/DeviceKeyRepository.java
  src/test/java/org/prgms/locomocoserver/user/application/UserServiceTest.java
Labels: feat

#154 feat: chatRoomDto mogakkoId 추가
  src/main/java/org/prgms/locomocoserver/chat/dto/ChatRoomDto.java
Labels: feat

#158 fix #157: 제대로 된 fetch join 문법으로 수정
  src/main/java/org/prgms/locomocoserver/categories/domain/CategoryRepository.java
Labels: fix

#162 Test 159 모각코 도메인 테스트
  build.gradle
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTest.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/participants/ParticipantRepositoryTest.java
Labels: feat, test

#163 Feature 160 모각코 리스트 최신순으로 보여주기
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/SearchType.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/searchpolicy/LocationSearchPolicy.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/mogakkotags/MogakkoTagRepository.java
  src/main/java/org/prgms/locomocoserver/mogakkos/dto/SearchRepositoryDto.java
  src/main/java/org/prgms/locomocoserver/mogakkos/presentation/MogakkoController.java
Labels: feat

#165 fix #162: 데드 라인은 모각코 종료 시간보다 앞에 있기만 하도록 수정
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTest.java
Labels: fix

#167 155 후기 커스텀 예외처리
  src/main/java/org/prgms/locomocoserver/global/exception/GlobalExceptionHandler.java
  src/main/java/org/prgms/locomocoserver/inquiries/application/InquiryService.java
  src/main/java/org/prgms/locomocoserver/review/exception/ReviewErrorType.java
  src/main/java/org/prgms/locomocoserver/review/exception/ReviewException.java
  src/test/java/org/prgms/locomocoserver/chat/application/ChatRoomServiceTest.java
Labels: feat

#170 168 모각코 채팅 삭제 연결
  src/main/java/org/prgms/locomocoserver/chat/application/ChatRoomService.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatMessageRepository.java
  src/main/java/org/prgms/locomocoserver/chat/domain/ChatParticipantRepository.java
  src/main/java/org/prgms/locomocoserver/global/filter/ExceptionHandlerFilter.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
Labels: feat

#169 Feature 161 모각코 예외 처리
  src/main/java/org/prgms/locomocoserver/inquiries/application/InquiryService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoParticipationService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/application/MogakkoService.java
  src/main/java/org/prgms/locomocoserver/mogakkos/domain/Mogakko.java
  src/main/java/org/prgms/locomocoserver/mogakkos/exception/MogakkoErrorCode.java
  src/main/java/org/prgms/locomocoserver/mogakkos/exception/MogakkoException.java
  src/test/java/org/prgms/locomocoserver/mogakkos/domain/MogakkoTest.java
Labels: feat

#172 171 신고 탈퇴한 회원 보이도록
  src/main/java/org/prgms/locomocoserver/report/application/ReportService.java
  src/main/java/org/prgms/locomocoserver/report/presentation/ReportController.java
Labels: fix
